##########################################################################
# Standard Properties
kotlin.code.style = official
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
org.gradle.warning.mode = fail
org.gradle.configuration-cache = true
##########################################################################
# Standard Fabric Dependencies
# Check these on https://fabricmc.net/develop/
minecraft_version = 1.21.10
yarn_mappings = 1.21.10+build.1
loader_version = 0.17.2
# Fabric API
fabric_version = 0.135.0+1.21.10
loom_version = 1.11-SNAPSHOT
java_version = 21
##########################################################################
# Mod Properties
mod_version = 0.3.0
maven_group = dev.kosmx.kowoconfig
archives_base_name = kotlin-owo-config
##########################################################################
# Kotlin Dependencies
# Check this on https://kotlinlang.org/docs/releases.html
kotlin_version = 2.2.20
# Check this on https://central.sonatype.com/artifact/com.google.devtools.ksp/com.google.devtools.ksp.gradle.plugin/
ksp_version = 2.2.20-2.0.4
# Check this on https://central.sonatype.com/artifact/com.squareup/kotlinpoet-ksp/
kotlin_poet_version = 2.2.0
# Check this on https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/
fabric_language_kotlin_version = 1.13.6+kotlin.2.2.20
##########################################################################
# 3rd Party Dependencies
# Check this on https://maven.wispforest.io/#/releases/io/wispforest/owo-lib/
owo_version = 0.12.22+1.21.9
# Check this on https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu/
mod_menu_version = 16.0.0-rc.1
